/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.util.SortedMap;
import java.util.TreeMap;

/**
 *
 * @author Samuel
 */
public class ElementView extends javax.swing.JFrame {

    /**
     * Creates new form ElementView
     */
    public ElementView(Element element_param) {
        initComponents();
        setLocationRelativeTo(null);
        this.element = element_param;
        setName(element.getName());
        Mass.setText(String.format("%f", element.getMassNumber()));
        Atomic.setText(String.format("%f", element.getAtomicNumber()));
    }
    
    public void setName(String name){
        jLabel1.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Mass_title = new javax.swing.JLabel();
        Mass = new javax.swing.JLabel();
        Atomic_title = new javax.swing.JLabel();
        Atomic = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setToolTipText("");

        Mass_title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Mass_title.setText("Mass:");

        Mass.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Mass.setText("jLabel2");

        Atomic_title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Atomic_title.setText("Atomic:");

        Atomic.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Atomic.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Mass_title)
                        .addGap(18, 18, 18)
                        .addComponent(Mass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Atomic_title)
                        .addGap(18, 18, 18)
                        .addComponent(Atomic)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mass_title)
                    .addComponent(Mass))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atomic)
                    .addComponent(Atomic_title))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElementView(new Element(element.getName(), element.getAtomicNumber(), element.getMassNumber(), element.getSymbol())).setVisible(false);
            }
        });
    }
    
    
    
   private static Element element;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel Atomic;
    private javax.swing.JLabel Atomic_title;
    private static javax.swing.JLabel Mass;
    private javax.swing.JLabel Mass_title;
    private static javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
